# Image logo support
set -g allow-passthrough on

# Escape mode latency
set -sg escape-time 0

# Defaults
set -g prefix C-Space
set -g mode-keys vi
set -g mouse on

# Status line
set -g @prefix_highlight_show_copy_mode "on"
set -g @prefix_highlight_show_sync_mode "on"

set -g status-left-length 50
set -g status-right-length 50
set -g status-left "#{prefix_highlight}[#S] "
set -g status-right "[#(whoami)@#H] %Y-%m-%d %H:%M [#{battery_percentage}]"

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-battery"
set -g @plugin "tmux-plugins/tmux-open"
set -g @plugin "tmux-plugins/tmux-pain-control"
set -g @plugin "tmux-plugins/tmux-prefix-highlight"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-sensible"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.tmux/plugins/tpm/tpm"
