[all_follow]
nixpkgs = "nixpkgs"

[inputs.darwin]
url = "github:nix-darwin/nix-darwin"

[inputs.neovim]
type = "fetch"
url = "github:neovim/neovim/nightly"

[inputs.nix-homebrew]
omit_inputs = ["brew-src"]
url = "github:zhaofengli/nix-homebrew"

[inputs.nixpkgs]
url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.zst"

[inputs.tack]
url = "github:manic-systems/tack"

[inputs.homebrew]
frozen = true
group = "brew"
tag = "{version}"
type = "fetch"
url = "github:Homebrew/brew"

[inputs.homebrew-cask]
frozen = true
group = "brew"
type = "fetch"
url = "github:Homebrew/homebrew-cask"

[inputs.homebrew-core]
frozen = true
group = "brew"
type = "fetch"
url = "github:Homebrew/homebrew-core"
