[all_follow]
nixpkgs = "nixpkgs"

[inputs.nixpkgs]
url = "https://channels.nixos.org/nixpkgs-unstable/nixexprs.tar.zst"

[inputs.darwin]
url = "github:nix-darwin/nix-darwin"

[inputs.neovim]
url = "github:neovim/neovim/nightly"
type = "fetch"

[inputs.nix-homebrew]
url = "github:zhaofengli/nix-homebrew"
follows = { brew-src = "homebrew" }

# These are manually pinned to decouple, update the <rev-or-ref> manually.
[inputs.homebrew]
url = "github:Homebrew/brew/7.0.1"
type = "fetch"

[inputs.homebrew-cask]
url = "github:Homebrew/homebrew-cask/7cb180869c4ff9cd6a822a92d8267a1579ef30de"
type = "fetch"

[inputs.homebrew-core]
url = "github:Homebrew/homebrew-core/2c70d8df74f9f227fefd7e197961d4cde9481fd2"
type = "fetch"
